services:
  postgres:
    container_name: postgres-sql-EcomAPI
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ecommercedb
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-EcomAPI
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  ecommerce-api:
    build: ./EcommerceAPI
    container_name: ecommerce-api
    ports:
      - 8088:8088
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommercedb
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIL_HOST: mail-dev
      SPRING_MAIL_PORT: 1025
    depends_on:
      - postgres
      - mail-dev
    networks:
      - spring-demo
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
